### PR TITLE
change license to MIT

### PR DESCRIPTION
**Pull request by krlvi**
i think a more permissive license would be better for this project. @kelvinelove @naXa777 @nickveenhof since you have contributions with the original license, i'd need your permission to change the license for all the code that's in main

### CODE REVIEW

**Comment by nickveenhof** [comment]
Permission granted!

**Comment by kelvinelove** [comment]
@krlvi permission granted...!!

**Comment by nickveenhof** [comment]
I've reached out  to @naXa777 through LinkedIn. Let's wait a bit longer. I'd hate to see this namespace get lost due to us not trying to reach out through all possible channels :)

**Comment by naXa777** [comment]
Permission granted.
sorry for the late reply

**Comment by nickveenhof** [comment]
Given everybody replied, I'm going ahead and merge this

**Pull request merged**
